services:
  frontend:
    image: harvesthill_frontend:latest
    container_name: harvesthill_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://24.199.93.70}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://24.199.93.70}
    env_file:
      - path: .env
        required: false
