# Generated by Django 5.2.16 on 2026-08-24 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySequenceCounter',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=255)),
                ('target_model', models.CharField(blank=True, max_length=255)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
