# Generated by Django 5.2.16 on 2026-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
