import os
import psycopg

db_url = os.environ.get('DATABASE_URL')
if not db_url:
    print("No DATABASE_URL set, skipping direct migration repair.")
    exit(0)

try:
    print("Connecting to PostgreSQL database to repair migration schema & history...")
    with psycopg.connect(db_url) as conn:
        with conn.cursor() as cur:
            # Ensure django_migrations table exists
            cur.execute("""
                CREATE TABLE IF NOT EXISTS django_migrations (
                    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    app character varying(255) NOT NULL,
                    name character varying(255) NOT NULL,
                    applied timestamp with time zone NOT NULL
                );
            """)

            # 1. Check for mismatched column data types (e.g. integer/bigint vs UUID)
            tables_to_check = [
                ('negotiations', 'negotiations_negotiationoffer'),
                ('negotiations', 'negotiations_negotiationthread'),
                ('delivery_notes', 'delivery_notes_deliverynote'),
                ('delivery_notes', 'delivery_notes_deliverynoteitem'),
                ('invoices', 'invoices_invoice'),
                ('notifications', 'notifications_notification'),
            ]

            for app_name, table_name in tables_to_check:
                cur.execute("""
                    SELECT data_type 
                    FROM information_schema.columns 
                    WHERE table_name = %s AND column_name = 'id';
                """, (table_name,))
                row = cur.fetchone()
                if row:
                    data_type = row[0].lower()
                    if 'uuid' not in data_type:
                        print(f"Table '{table_name}' has legacy non-UUID 'id' ({data_type}). Dropping table and resetting '{app_name}' migrations...")
                        cur.execute(f"DROP TABLE IF EXISTS {table_name} CASCADE;")
                        cur.execute("DELETE FROM django_migrations WHERE app = %s;", (app_name,))

            # 2. Repair missing sequence history for products app
            cur.execute("SELECT name FROM django_migrations WHERE app='products';")
            rows = [r[0] for r in cur.fetchall()]

            products_migrations = [
                '0001_initial',
                '0002_product_created_at_product_description',
                '0003_alter_product_image',
                '0004_product_discount_price_product_is_discounted',
                '0005_product_preferred_harvest_period_and_more',
                '0006_product_offered_price_product_pricing_mode',
                '0007_product_display_id',
                '0008_product_target_clients_product_visibility_scope',
                '0009_product_archived_at_freshdeal',
                '0010_productimage'
            ]

            max_applied_idx = -1
            for idx, mig in enumerate(products_migrations):
                if mig in rows:
                    max_applied_idx = idx

            if max_applied_idx >= 0:
                for idx in range(0, max_applied_idx):
                    mig_name = products_migrations[idx]
                    if mig_name not in rows:
                        print(f"Fixing missing migration record: products.{mig_name}")
                        cur.execute(
                            "INSERT INTO django_migrations (app, name, applied) VALUES ('products', %s, NOW());",
                            (mig_name,)
                        )

            conn.commit()
            print("Successfully verified and repaired django_migrations history and column schemas!")
except Exception as err:
    print("Migration repair notice:", err)
