# Generated by Django 5.2.16 on 2026-08-12 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('discrepancy', 'Discrepancy')], default='pending', max_length=20)),
                ('details', models.TextField()),
                ('signed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted_by_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='orders.order')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='supplies.supply')),
            ],
        ),
    ]
