# Generated by Django 5.2.16 on 2026-07-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_notes', '0002_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='supplies.supply'),
        ),
    ]
