# Generated by Django 5.2.16 on 2026-07-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='signed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
