# Generated by Django 5.2.16 on 2026-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_notes', '0004_deliverynote_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
