# Generated by Django 5.2.16 on 2026-08-24 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_product_name', models.CharField(blank=True, default='', max_length=255)),
                ('custom_category', models.CharField(blank=True, default='', max_length=100)),
                ('custom_unit', models.CharField(blank=True, default='kg', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced')], default='pending', max_length=20)),
                ('visibility_scope', models.CharField(choices=[('HARVEST_HILL_ONLY', 'Harvest Hill Delivery Only'), ('SPECIFIC_CLIENTS', 'Specific Chosen Clients'), ('REGISTERED_CLIENTS', 'All Registered Clients'), ('PUBLIC', 'Public Marketplace'), ('private_admin', 'Harvest Hill Delivery Only'), ('specific_clients', 'Specific Chosen Clients'), ('all_clients', 'All Registered Clients'), ('public', 'Public Marketplace')], default='HARVEST_HILL_ONLY', max_length=30)),
                ('is_suggested_product', models.BooleanField(default=False)),
                ('suggested_product_name', models.CharField(blank=True, default='', max_length=255)),
                ('disclose_farmer_name', models.BooleanField(default=False)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='supplies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulk_min_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('rating_count', models.IntegerField(default=1)),
                ('supply_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='accounts.farmerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='products.product')),
                ('target_clients', models.ManyToManyField(blank=True, related_name='exclusive_supplies', to='accounts.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='supplies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplies.supply')),
            ],
        ),
    ]
