# Generated by Django 5.2.16 on 2026-08-12 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_product_name', models.CharField(blank=True, default='', max_length=255)),
                ('custom_category', models.CharField(blank=True, default='', max_length=100)),
                ('custom_unit', models.CharField(blank=True, default='kg', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced')], default='pending', max_length=20)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('quality_grade', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supplies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulk_min_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('rating_count', models.IntegerField(default=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='accounts.farmerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='supplies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplies.supply')),
            ],
        ),
    ]
