# Generated by Django 5.2.16 on 2026-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='accepted_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='disclose_farmer_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supply',
            name='is_suggested_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supply',
            name='suggested_product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supply',
            name='target_clients',
            field=models.ManyToManyField(blank=True, related_name='exclusive_supplies', to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='supply',
            name='visibility_scope',
            field=models.CharField(choices=[('private_admin', 'Harvest Hill Delivery Only'), ('specific_clients', 'Specific Chosen Clients'), ('all_clients', 'All Registered Clients'), ('public', 'Public (All Visitors)')], default='private_admin', max_length=30),
        ),
    ]
