# Generated by Django 5.2.16 on 2026-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supply',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='supplies/'),
        ),
        migrations.AddField(
            model_name='supply',
            name='quality_grade',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced')], default='pending', max_length=20),
        ),
    ]
