# Generated by Django 5.2.16 on 2026-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_supply_available_date_supply_notes_supply_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
