# Generated by Django 5.2.16 on 2026-08-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_supply_accepted_quantity_supply_agreed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='supplies/'),
        ),
    ]
