# Generated by Django 5.2.16 on 2026-08-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_supply_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supply_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
