# Generated by Django 5.2.16 on 2026-07-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='supplies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplies.supply')),
            ],
        ),
    ]
