# Generated by Django 5.2.16 on 2026-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_supply_supply_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='visibility_scope',
            field=models.CharField(choices=[('HARVEST_HILL_ONLY', 'Harvest Hill Delivery Only'), ('SPECIFIC_CLIENTS', 'Specific Chosen Clients'), ('REGISTERED_CLIENTS', 'All Registered Clients'), ('PUBLIC', 'Public Marketplace'), ('private_admin', 'Harvest Hill Delivery Only'), ('specific_clients', 'Specific Chosen Clients'), ('all_clients', 'All Registered Clients'), ('public', 'Public Marketplace')], default='HARVEST_HILL_ONLY', max_length=30),
        ),
    ]
