# Generated by Django 5.2.16 on 2026-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_alter_supply_visibility_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=20, null=True),
        ),
    ]
