# Generated by Django 5.2.16 on 2026-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_alter_supply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced')], default='pending', max_length=20),
        ),
    ]
