# Generated by Django 5.2.16 on 2026-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_supply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
