# Generated by Django 5.2.16 on 2026-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_supply_discount_price_supply_is_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='supply',
            name='rating_count',
            field=models.IntegerField(default=1),
        ),
    ]
