# Generated by Django 5.2.16 on 2026-08-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productrequest'),
        ('supplies', '0008_supply_rating_supply_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='custom_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='supply',
            name='custom_product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supply',
            name='custom_unit',
            field=models.CharField(blank=True, default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='supply',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='products.product'),
        ),
    ]
