# Generated by Django 5.2.16 on 2026-08-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_supply_custom_category_supply_custom_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='bulk_min_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
