# Generated by Django 5.2.16 on 2026-08-24 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_farmer', models.BooleanField(default=False)),
                ('deleted_by_client', models.BooleanField(default=False)),
                ('status', models.CharField(default='open', max_length=20)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_negotiations', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_threads', to='supplies.supply')),
            ],
        ),
        migrations.CreateModel(
            name='NegotiationOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('is_offer', models.BooleanField(default=True)),
                ('offer_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COUNTERED', 'Countered'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_farmer', models.BooleanField(default=False)),
                ('deleted_by_admin', models.BooleanField(default=False)),
                ('deleted_by_client', models.BooleanField(default=False)),
                ('parent_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_counter_offers', to='negotiations.negotiationoffer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiations.negotiationthread')),
            ],
        ),
    ]
