# Generated by Django 5.2.16 on 2026-07-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negotiations', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationthread',
            name='supply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_thread', to='supplies.supply'),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiations.negotiationthread'),
        ),
    ]
