# Generated by Django 5.2.16 on 2026-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationoffer',
            name='deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='deleted_by_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
