# Generated by Django 5.2.16 on 2026-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationthread',
            name='deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiationthread',
            name='deleted_by_farmer',
            field=models.BooleanField(default=False),
        ),
    ]
