# Generated by Django 5.2.16 on 2026-08-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0002_negotiationoffer_deleted_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationoffer',
            name='is_offer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='offer_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COUNTERED', 'Countered'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='parent_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_counter_offers', to='negotiations.negotiationoffer'),
        ),
        migrations.AddField(
            model_name='negotiationoffer',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='negotiationoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='negotiationoffer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
