# Generated by Django 5.2.16 on 2026-07-22 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0003_negotiationthread_deleted_by_client_and_more'),
        ('supplies', '0004_supplyimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationthread',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_negotiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiationthread',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='negotiationthread',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_threads', to='supplies.supply'),
        ),
    ]
