# Generated by Django 5.2.16 on 2026-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
