# Generated by Django 5.2.16 on 2026-07-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
