# Generated by Django 5.2.16 on 2026-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_deleted_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_quantity_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
