# Generated by Django 5.2.16 on 2026-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_quantity_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_assessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
