# Generated by Django 5.2.16 on 2026-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
