# Generated by Django 5.2.16 on 2026-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
