# Generated by Django 5.2.16 on 2026-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='business_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
