# Generated by Django 5.2.16 on 2026-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_scheduled_deletion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('farm_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('crops', models.TextField(blank=True, default='')),
                ('certifications', models.TextField(blank=True, default='')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
