# Generated by Django 5.2.16 on 2026-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_farmerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerapplication',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
