# Generated by Django 5.2.16 on 2026-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_farmerapplication_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='payment_account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='payment_method',
            field=models.CharField(blank=True, default='MTN Mobile Money (MoMo)', max_length=100),
        ),
    ]
