# Generated by Django 5.2.16 on 2026-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminprofile_avatar_clientprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
