# Generated by Django 5.2.16 on 2026-08-24 10:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_currently_needed', models.BooleanField(default=False)),
                ('urgency', models.CharField(default='low', max_length=20)),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('pricing_mode', models.CharField(choices=[('harvest_hill_offers', 'Harvest Hill Offers'), ('farmer_proposes', 'Farmer Proposes')], default='harvest_hill_offers', max_length=30)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='products/')),
                ('quantity_needed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visibility_scope', models.CharField(choices=[('HARVEST_HILL_ONLY', 'Harvest Hill Delivery Only'), ('SPECIFIC_CLIENTS', 'Specific Chosen Clients'), ('REGISTERED_CLIENTS', 'All Registered Clients'), ('PUBLIC', 'Public Marketplace'), ('private_admin', 'Harvest Hill Delivery Only'), ('specific_clients', 'Specific Chosen Clients'), ('all_clients', 'All Registered Clients'), ('public', 'Public Marketplace')], default='PUBLIC', max_length=30)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('quality_requirements', models.TextField(blank=True, default='')),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('preferred_harvest_period', models.CharField(blank=True, default='', max_length=255)),
                ('target_clients', models.ManyToManyField(blank=True, related_name='exclusive_products', to='accounts.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FreshDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount Off'), ('PERCENTAGE', 'Percentage Off')], default='FIXED', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('ABORTED', 'Aborted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fresh_deals', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to='products/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('preferred_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='accounts.clientprofile')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
