# Generated by Django 5.2.16 on 2026-08-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_price_product_is_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_harvest_period',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
