# Generated by Django 5.2.16 on 2026-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_preferred_harvest_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('harvest_hill_offers', 'Harvest Hill Offers'), ('farmer_proposes', 'Farmer Proposes')], default='harvest_hill_offers', max_length=30),
        ),
    ]
