# Generated by Django 5.2.16 on 2026-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_offered_price_product_pricing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
