# Generated by Django 5.2.16 on 2026-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0007_product_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target_clients',
            field=models.ManyToManyField(blank=True, related_name='exclusive_products', to='accounts.clientprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='visibility_scope',
            field=models.CharField(choices=[('HARVEST_HILL_ONLY', 'Harvest Hill Delivery Only'), ('SPECIFIC_CLIENTS', 'Specific Chosen Clients'), ('REGISTERED_CLIENTS', 'All Registered Clients'), ('PUBLIC', 'Public Marketplace'), ('private_admin', 'Harvest Hill Delivery Only'), ('specific_clients', 'Specific Chosen Clients'), ('all_clients', 'All Registered Clients'), ('public', 'Public Marketplace')], default='PUBLIC', max_length=30),
        ),
    ]
