# Generated by Django 5.2.16 on 2026-08-20 06:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_target_clients_product_visibility_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FreshDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount Off'), ('PERCENTAGE', 'Percentage Off')], default='FIXED', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('ABORTED', 'Aborted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fresh_deals', to='products.product')),
            ],
        ),
    ]
